config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "posts#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :users do
    resources :follow_requests, only: [:create, :update, :destroy]
  end
  resources :posts do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commenter, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post
end

app/models/follow_request.rb
class FollowRequest < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :user

  has_many :likes
  has_many :comments

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
include Gravtastic
gravtastic

after_create :send_welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes
  has_many :comments

  has_one_attached :photo

  has_many :follow_requests_as_follower, class_name: 'FollowRequest', foreign_key: 'follower_id'
  has_many :follow_requests_as_followee, class_name: 'FollowRequest', foreign_key: 'followee_id'

  has_many :followers, through: :follow_requests_as_followee, source: :follower
  has_many :followees, through: :follow_requests_as_follower, source: :followee



  def following?(other_user)
    follow_requests_as_follower.where(followee: other_user).exists?
  end


  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    puts params.inspect
    @comment = @post.comments.build(comment_params)
    @comment.commenter = current_user

    if @comment.save
      redirect_to @post, notice: "Your comment was posted!"
    else
      puts @comment.errors.full_messages if @comment.errors.any?
      flash.now[:danger] = "Your comment wasn't posted!"
      render 'posts/show'
    end
  end


  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.commenter == current_user
      if @comment.destroy
        redirect_to @post, notice: "Comment was successfully deleted."
      else
        redirect_to @post, alert: "Comment could not be deleted."
      end
    else
       # Redirect the user with an error message if they are not the commenter
       redirect_to @post, alert: "You can only delete your own comments."
      end
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :body, :commenter, :post_id, :user_id)
  end
end

app/controllers/follow_requests_controller.rb
class FollowRequestsController < ApplicationController
  before_action :authenticate_user!

def create
  followee = User.find(params[:followee_id])
  @follow_request = current_user.follow_requests_as_follower.build(followee: followee, status: 'pending')

  if @follow_request.save
    redirect_to users_path, notice: 'Follow request sent.'
  else
    redirect_to users_path, alert: 'Unable to send follow request.'
  end
end


def destroy
  follow_request = FollowRequest.find_by(follower_id: current_user.id, followee_id: params[:id])
  if follow_request&.destroy
    redirect_to users_path, notice: 'Successfully unfollowed.'
  else
    redirect_to users_path, alert: 'Unable to unfollow.'
  end
end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_to posts_path
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    # Fetch the IDs of users the current user is following
    following_ids = current_user.followees.pluck(:id)

    # Fetch posts from followed users excluding the current user's own posts
    @followed_users_posts = Post.where(user_id: following_ids).order(created_at: :desc)

    # Fetch posts created by the current user
    @created_posts = current_user.posts.order(created_at: :desc)

    # Fetch posts liked by the current user
    @liked_posts = Post.joins(:likes).where(likes: { user_id: current_user.id }).order('likes.created_at DESC')

    # Fetch all posts
    @all_posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user == current_user
      @post.destroy
      redirect_to posts_path, notice: 'Post was successfully destroyed.'
    else
      redirect_to @post, alert: 'You are not authorized to delete this post.'
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @comments = Comment.where(commenter:current_user)
    @followers = @user.followers
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end



  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follow_requests_helper.rb
module FollowRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<div class="buttons-container">
  <%= link_to 'My Profile', user_path(current_user), class: 'sticky-top-btn btn btn-primary' %>
  <%= link_to 'All Users', users_path, class: 'sticky-top-btn btn btn-primary' %>
  <%= link_to 'Posts', posts_path, class: 'sticky-top-btn btn btn-primary' %>
  <%= link_to 'New Post', new_post_path, class: 'sticky-top-btn btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odinbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="banner">
  <%= link_to 'Odinbook', posts_path, class: 'banner-link' %>
</div>
  </div>
   <% flash.each do |type, message| %>
      <div class="flash <%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_posts_list.html.erb
<% posts.each do |post| %>
  <div style="border: 1px solid #333; padding: 10px; margin-bottom: 10px;">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <% if post.image.attached? %>
      <%= link_to post_path(post) do %>
        <%= image_tag post.image.variant(resize_to_limit: [500, 500]), class: "post-image" %>
      <% end %>
    <% end %>
    <p><%= post.body %></p> 
      <p>Author: <%= link_to user_path(post.user) do %>
                <% if post.user.photo.attached? %>
                  <%= image_tag post.user.photo.variant(resize_to_limit: [100, 100]), class: "author-profile-picture" %>
                <% else %>
                  <%= image_tag post.user.gravatar_url, alt: "User's Gravatar", class: "author-profile-picture" %> <!--otherwise use the gravatar -->
                <% end %>
              <% end %>
      <p> <a href="/users/<%= post.user.id %>"><%= post.user.email %></a>  </p>
    </p>
    <p>Likes: <%= post.likes.count %></p>
    <p>Comments: <%= post.comments.count %></p>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'layouts/navigation' %>
<%= form_with(model: @post, local: true) do |form| %>
   <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
    <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <%= form.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Created Posts</h1>

<%= render 'layouts/navigation' %>

<%= render partial: "posts_list", locals: { posts: @created_posts } %>

<h1>Liked Posts</h1>
<%= render partial: "posts_list", locals: { posts: @liked_posts } %>

<h1>Posts from Followed Users</h1>
<%= render partial: "posts_list", locals: { posts: @followed_users_posts } %>

<h1>All Posts</h1>
<%= render partial: "posts_list", locals: { posts: @all_posts } %>

<nav>
    <ul>
    <li><%= link_to "Users", users_path %></li>
    <li><%= link_to "New Post", new_post_path %></li>
    <li><%= link_to "Edit user : #{current_user.email}", edit_user_registration_path %></li>
    </ul>
</nav>

app/views/posts/new.html.erb
<%= render 'layouts/navigation' %>
<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1> 
<%= render 'layouts/navigation' %>

<% if @post.image.attached? %> <!-- Check if the post has an attached image -->
  <%= image_tag @post.image.variant(resize_to_limit: [500, 500]), class: "post-image" %> 
<% end %>

<p><%= @post.body %></p> 

<p><strong>Author:</strong> <%= @post.user.email %></p> 

<% if user_signed_in? && !current_user.likes.exists?(post: @post) %> <!-- Check if the user is signed in and if they haven't liked the post -->
  <%= button_to 'Like', likes_path(post_id: @post.id), method: :post %> <!-- Display a button to like the post -->
<% else %>
  <%= button_to 'Unlike', like_path(current_user.likes.find_by(post: @post).id), method: :delete %> <!-- Display a button to unlike the post -->
<% end %>
<% if current_user == @post.user %> <!-- Check if the current user is the author of the post -->
  <%= link_to 'Edit', edit_post_path(@post) %> | 
<% end %>
<%= link_to 'Back', posts_path %> 

<%= button_to 'Destroy', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %> 

<%= form_with(model: [@post, Comment.new], local: true) do |f| %> <!-- Display a form to create a new comment for the post -->
  <p>
    <%= f.label :body, "New comment" %><br> 
    <%= f.text_area :body %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

<% @post.comments.each do |comment| %> <!-- Iterate over each comment associated with the post -->
  <p>
    <strong><%= comment.commenter.email %></strong> 
    <%= comment.body %> 
    <%= button_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %> 
  </p>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= render 'layouts/navigation' %>

<% @users.each do |user| %>
    <div class="post" style="border: 1px solid #333; padding: 10px; margin-bottom: 10px;">
        <%= link_to user_path(user) do %> <!--makes the user name and picture a link to his profile-->
            <% if user.photo.attached? %> <!--checks if the user has uploaded a profile picture-->
                <%= image_tag user.photo.variant(resize_to_limit: [300, 300]), alt: "User's Photo", class: "user-photo" %>
            <% else %>
                <%= image_tag user.gravatar_url, alt: "User's Gravatar" %> <!--otherwise use the gravatar -->
            <% end %>
            <h1><%= user.email %></h1>
        <% end %>
        <% if current_user != user %>  <!--if logged user isn't the same as this one and not already following, permit the form to add a follow -->
            <% if !current_user.following?(user) %>
                <%= form_with url: user_follow_requests_path(user), method: :post do |form| %>
                    <%= form.hidden_field :followee_id, value: user.id %>
                    <%= form.submit "Follow" %>
                <% end %>
            <% else %>
                <%= form_with url: user_follow_request_path(current_user, user), method: :delete do |form| %>
                    <%= form.submit "Unfollow" %>
                <% end %>
            <% end %>
        <% end %>
    </div>
<% end %>

<%= link_to 'home', posts_path %>

app/views/users/show.html.erb
<h1>User Profile</h1>

<%= render 'layouts/navigation' %>

<div class="user-info">
    <div class="user-avatar">
        <% if @user.photo.attached? %>
            <%= image_tag @user.photo.variant(resize_to_limit: [500, 500]), alt: "User's Photo", class: "user-photo" %>
        <% else %>
            <% gravatar_url = "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email.downcase)}" %>
            <%= image_tag(gravatar_url, alt: "User Avatar") %>
        <% end %>
    </div>
        <% if current_user != @user %>  <!--if logged user isn't the same as this one and not already following, permit the form to add a follow -->
            <% if !current_user.following?(@user) %>
                <%= form_with url: user_follow_requests_path(@user), method: :post do |form| %>
                    <%= form.hidden_field :followee_id, value: @user.id %>
                    <%= form.submit "Follow" %>
                <% end %>
            <% else %>
                <%= form_with url: user_follow_request_path(current_user, @user), method: :delete do |form| %>
                    <%= form.submit "Unfollow" %>
                <% end %>
            <% end %>
        <% end %>
    <div class="user-details">
        <p>Email: <%= @user.email %></p>
    </div>
</div>

<h2>Posts from <%= @user.email %> :</h2>
<%= render partial: "posts/posts_list", locals: { posts: @user.posts.order(created_at: :desc) } %>

<div class="user-followers">
  <h2>Followers</h2>
  <ul>
    <% @followers.each do |follower| %>
      <li>
        <%= link_to follower.email, user_path(follower) %> 
      </li>
    <% end %>
  </ul>
</div>

<li><%= link_to "Edit user : #{current_user.email}", edit_user_registration_path %></li>
<%= link_to "Log out", destroy_user_session_path, method: :delete, 'data-turbolinks': 'false' %>